### ISSUE TITLE
Create pypi version of topology processor

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/topology-processor#24]
Create project structure for topology processor that will be used in the gridappsd platform.

```[tasklist]
### Tasks
- [x] Add dev release workflow
- [ ] Add release workflow
```

**Comment by craig8** [comment]
https://github.com/GRIDAPPSD/topology-processor/pull/25

**Comment by AAndersn** [comment]
no longer needed. PyPi version will instead be based on https://github.com/PNNL-CIM-Tools/CIM-Graph-Topology-Processor
